# Generated by Django 2.1.3 on 2018-11-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_text', models.CharField(max_length=32, verbose_name='触发文本')),
                ('response_text', models.CharField(max_length=128, verbose_name='响应文本')),
                ('been_triggered_for', models.IntegerField(verbose_name='触发次数')),
                ('last_triggered_at', models.DateTimeField(verbose_name='上次触发时间')),
                ('last_triggered_by', models.CharField(max_length=128)),
                ('added_by', models.CharField(max_length=128, verbose_name='添加用户')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='TeleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele_id', models.CharField(max_length=32, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last Name')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('is_bot', models.BooleanField(verbose_name='是机器人吗?')),
                ('json_data', models.CharField(max_length=1024, verbose_name='json data')),
                ('status', models.CharField(max_length=32, verbose_name='现在所处模式')),
                ('status_since', models.DateTimeField(verbose_name='进入模式时间')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
        ),
    ]
